chore: add {Darma Al Gani} as 2024 Academician
Daskom-Lab/2024-Academy pull request #63
Opened 2024-08-18 13:33 UTC by Daarma-IC

2024-08-18 17:23 UTC, fakhrip requested changes
![Screenshot_2024_0819_001841.jpg](https://github.com/user-attachments/assets/e3ca38ba-cfba-4c09-8cc5-54244d7e9aa4)

Please dont change other lines, since it will change the formatting as well (see the one with Rafhan Mazaya)

Change only what you need to change which in this case is just to **add** your name and stuff 👍

Please fix it once again, thanks!

2024-08-18 17:23 UTC, fakhrip commented on Readme.md
> +
Please remove this newline here as its not needed

2024-08-19 05:06 UTC, Daarma-IC reviewed
Deleted line 86,87

2024-08-19 05:53 UTC, fakhrip commented
You have just added your personal web codes here again 😅 , okay so good thing is that you might be learning a lot from all these here, so the thing is that you would want to push your personal web codes to another repo of yours instead of the fork of this repo

Please remove it along with the fix that i have mentioned previously, and also please click on this re-request review icon beside the red icon thingy when youre done, thanks!
![image](https://github.com/user-attachments/assets/0cc9ce70-bed8-44ba-afab-9f4d9ea8ae16)

If you have any question, i suggest you to ask to the tentors or mentors to understand what is the right thing to do here 👍

2024-08-19 07:25 UTC, Daarma-IC commented
sorry about it and promise me, and now im already deleted what i make change before, thanks for your pleasure

2024-08-19 11:15 UTC, Daarma-IC reviewed
Already create and update the newest

2024-08-19 13:36 UTC, closed without merging